sudo: required

notifications:
  email: false

language: python
cache: pip

matrix:
  include:
  # mitogen_tests.sh
  - python: "2.7"
    env: MODE=mitogen MITOGEN_TEST_DISTRO=debian
  - python: "2.7"
    env: MODE=mitogen MITOGEN_TEST_DISTRO=centos
  - python: "3.6"
    env: MODE=mitogen MITOGEN_TEST_DISTRO=debian

  # debops
  - python: "2.7"
    env: MODE=debops_common

  # ansible
  - python: "2.7"
    env: MODE=ansible ANSIBLE_VERSION=2.4.3.0 MITOGEN_TEST_DISTRO=debian
  - python: "2.7"
    env: MODE=ansible ANSIBLE_VERSION=2.4.3.0 MITOGEN_TEST_DISTRO=centos
  - python: "2.7"
    env: MODE=ansible ANSIBLE_VERSION=2.5.0 MITOGEN_TEST_DISTRO=centos
  - python: "2.7"
    env: MODE=ansible ANSIBLE_VERSION=2.5.0 MITOGEN_TEST_DISTRO=debian


install:
- pip install -r dev_requirements.txt

script:
- ${TRAVIS_BUILD_DIR}/.travis/${MODE}_tests.sh

services:
  - docker
